### ISSUE TITLE
Оформление репозитория

### ISSUE THREAD

**Issue by tshemsedinov** [Destaby/Web#1]
- [ ] Добавить eslint и конфигурацию, лучше взять эту: [.eslintrc.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json)
- [ ] Добавить `README.md` 1-2 страницы описания проекта и кода
- [ ] Добавить лицензию, например MIT
- [ ] Добавить `package.json` с зависимостями, тем же eslint. Пример: [package.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/package.json)

**Comment by Destaby** [comment]
Добрый день.

Я сделал другой репозиторий для курсовой и использовал все требования. Я
создал новый репозиторий, потому что прежний репозиторий по некоторым
обстоятельствам нужен мне в том виде, в котором есть.
Жду Ваших указаний. Ниже ссылка.

https://github.com/Destaby/Chuck-Norris-Jokes.git

С уважением,
Николай Рудык
